name: CI
on: [pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CLICOLOR_FORCE: 1
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  ci:
    name: CI
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        rust: [stable]
        os: [ubuntu-latest,ubuntu-24.04-arm]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}
    - name: Install cargo-make
      run: cargo install --debug cargo-make
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2
    - name: Run CI
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      if: matrix.rust == 'stable' || matrix.rust == 'beta' || matrix.rust == 'nightly'
      run: cargo run --bin cargo-make --target-dir target/ci -- make --env "CODECOV_TOKEN=${CODECOV_TOKEN}" ci-flow
